name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: Anand

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           echo ${{ secrets.PASSWORD}} | sudo docker build . -t website  
           echo ${{ secrets.PASSWORD}} | sudo docker run -itd --name website -p5000:80 website:latest 
