name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           timestamp=$(date +'%d%m%y%h%m%s')
           echo ${{ secrets.PASSWORD}} | sudo docker build . -t website:$timestamp  
           #echo ${{ secrets.PASSWORD}} | sudo docker run -itd  -p5000:80 website:$timestamp 
           echo ${{ secrets.PASSWORD}} | sudo docker tag website ntsanand/website:$timestamp
           echo ${{ secrets.PASSWORD}} | sudo docker login -u ntsanand -p Anand1997@ $DOCKER_REGISTRY 
           echo ${{ secrets.PASSWORD}} | sudo docker push ntsanand/website:$timestamp
