name: Node.js Package

on:
  push:
    branches: main
    

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: check out the code
      - uses: actions/checkout@v3
      - name: build 
      - run: |
           echo ${{ secrets.PASSWORD}} | sudo docker build . -t website  
           echo ${{ secrets.PASSWORD}} | sudo docker run -itd --name website -p5000:80 website:latest  

